apigw_sub_domain       = "webcache"
apigw_domain           = "example.net"
lambda_name            = "es_webcache"
acm_domain_name        = "example.net"
production_domain      = "www.example.com"
production_domain_cert = "example.com"